version: 0.1
log:
    level: debug
    formatter: text
    fields:
        service: registry
        environment: ENVIRONMENT
storage:
    s3:
        accesskey: AWS_ACCESS_KEY
        secretkey: AWS_SECRET_KEY
        region: AWS_REGION
        bucket: S3_BUCKET
        secure: true
        v4auth: true   
    cache:
        layerinfo: redis
reporting:
    newrelic:
        licensekey: NR_TOKEN
        name: registry
        verbose: true
http:
    addr: :5000
    secret: HTTP_SECRET
redis:
    addr: REDIS_ENDPOINT
    password: REDIS_PASSWORD
    pool:
        maxidle: 16
        maxactive: 64
        idletimeout: 300s
